### ISSUE TITLE
Support hosted Jira instances with personal access tokens?

### ISSUE THREAD

**Issue by pwright** [adyscorpius/logseq-jira#2]
maybe a feature request?

https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

**Comment by adyscorpius** [comment]
Hi, thanks for the suggestion.. 

I think this relates to self-hosted Jira instances, which this plugin doesn't support at present. 

Definitely something to look at in the future.

**Comment by nightscape** [comment]
Hi @juanirm, you might be interested in this:
https://github.com/adyscorpius/logseq-jira/pull/6
Side note: I recommend always having a short look at the open issues and pull requests for any project which doesn't work immediately as expected.

**Comment by juanirm** [comment]
Hi @nightscape ,

Nice feat submission. Hope it gets merged.

As per the open issues, though you are right and one should look for those before getting into a plugin or tool, the fact that this only works for cloud means that it was a scope decision. In my opinion those should be documented same as any requirement the tool might have.

cheers

**Comment by adyscorpius** [comment]
Hi. Thanks for the interest around this. The end of life for self hosted instances is Feb 2024, so I don't intend to support it in the plugin myself. But if at least 3 people can manage and validate that it works, I'll merge the pull request.

**Comment by adyscorpius** [comment]
> I just spent 30 minutes trying to get this plugin to work with our hosted Jira instance to finally find this :(
> 
> I think people could benefit from having this clearly stated in the plugin description :)
> 
> Really looking forward to this being compatible with hosted instances.

It does mention it in the README, maybe not so obvious.

**Comment by FabianMNoss** [comment]
> But if at least 3 people can manage and validate that it works, I'll merge the pull request.
Then I'll be at least number one of those three :)

**Comment by adyscorpius** [comment]
Would you be able to offer a project/user account on a self hosted instance to test this out?

**Comment by FabianMNoss** [comment]
> Would you be able to offer a project/user account on a self hosted instance to test this out?

Unfortunately not, the self hosted instance is a company one...
But as I was a developer (not actively working in this area since a few years), I could support in testing and debugging. Would this be an option?

**Comment by adyscorpius** [comment]
I just merged the pull request for support of on-premise Jira. Do check it out and tell me how it works.

**Comment by adyscorpius** [comment]
This should be fixed now with v.0.3.0 onwards. Please confirm and close the issue if it works.

**Comment by adyscorpius** [comment]
v0.4.1 fixes PAT not working properly. Can someone confirm? Thanks.

**Comment by jwhonce** [comment]
@adyscorpius v0.4.1 works for me. Thank you for all. your hard work!

**Comment by adyscorpius** [comment]
That's great. Glad to have it working.
