### ISSUE TITLE
v0.0.8 - Bug with Logseq causing block text not to update.

### ISSUE THREAD

**Issue by dv-adit** [adyscorpius/logseq-jira#4]
In v0.0.8, while block properties get added, the main text doesn't update. This relates to a bug in Logseq tracked here..

[Using upsertBlockProperty after updateBlock resets update back to previous value](https://github.com/logseq/logseq/issues/8686)

Waiting for the issue to be fixed to automatically fix this issue.

**Comment by adyscorpius** [comment]
Fixed in subsequent versions.
