### ISSUE TITLE
Mixed line endings in repo

### ISSUE THREAD

**Issue by nightscape** [adyscorpius/logseq-jira#8]
Hi @adyscorpius, this might come off as super-nitpicky, but some files have different line endings:
```
git ls-files --eol
i/lf    w/lf    attr/                   .github/workflows/publish.yml
i/lf    w/lf    attr/                   .gitignore
i/lf    w/lf    attr/                   CODE_OF_CONDUCT.md
i/lf    w/lf    attr/                   LICENSE
i/crlf  w/crlf  attr/                   README.md
i/-text w/-text attr/                   demo.gif
i/-text w/-text attr/                   jira.png
i/lf    w/lf    attr/                   package-lock.json
i/lf    w/lf    attr/                   package.json
i/crlf  w/crlf  attr/                   src/index.html
i/crlf  w/crlf  attr/                   src/index.ts
i/lf    w/lf    attr/                   src/settings.ts
i/lf    w/lf    attr/                   tsconfig.json
```

I'm just trying to rebase my PR #6, but I'm having a hard time convincing VS Code to not replace the `crlf` with `lf` while still keeping my changes.
Personally, I always enable `autocrlf` and haven't had any line ending problems ever since:
```bash
git config --global core.autocrlf input
```

Here's some [documentation on how to get rid of the mixed line endings](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings).

**Comment by adyscorpius** [comment]
Hi, thanks for the recommendation. I added .gitattributes to make that by default and also updated the files with crlf line endings.

**Comment by nightscape** [comment]
Cool, thanks!
